name: sole_seekers
description: A final year Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  # firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_ui_firestore: ^1.6.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  smooth_page_indicator: ^1.1.0

  # flutter_native_splash:
 
# flutter_native_splash:
#   android: true
#   ios: true

#   color: "#F7FAF7" 
#   image: "assets/SoleSeekers Light.png"


dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/SoleSeekers app icon.jpg"

  flutter_lints: ^2.0.0
    
flutter:
  assets:
    - assets/
  uses-material-design: true
